export function App() {
  return <main className="site-shell">
    <nav className="site-nav" aria-label="Website navigation"><a className="wordmark" href="#top" aria-label="Relintor home"><img className="brand-logo" src="/relintor-logo.png" alt="Relintor" /></a><div><a href="#how-it-works">How it works</a><a href="#proof">Proof boundary</a><a className="nav-cta" href="#takeover">Take over a project</a></div></nav>
    <section className="hero" id="top" aria-labelledby="hero-title">
      <div className="hero-copy"><p className="eyebrow">EXECUTION AUTHORITY FOR AI-BUILT SOFTWARE</p><h1 id="hero-title">Your AI can say it finished. Relintor makes it prove it.</h1><p className="hero-lede">Describe the outcome, find the missing decisions, seal the scope, and supervise Antigravity until requirements are accounted for and evidence matches.</p><div className="hero-actions"><a className="button button-dark" href="/downloads/Relintor_0.1.0_x64-setup.exe" download="Relintor_0.1.0_x64-setup.exe">Download for Windows</a><a className="button button-light" href="#takeover">Take over a project</a></div><p className="download-note">Windows x64 · Closed Beta</p><p className="truth-note">External billing, provider availability, signing, and cross-platform release certification remain explicit release gates.</p></div>
      <div className="hero-object" aria-label="Relintor proof object"><span>FIELD NOTE 01</span><strong>PROOF<br />BEFORE<br />DONE</strong><small>requirements · evidence · recovery</small></div>
    </section>
    <section className="proof-strip" id="proof" aria-label="Product proof promises"><span>Requirements accounted</span><span>Evidence attached</span><span>Safe recovery</span><span>No API keys</span></section>
    <section className="workflow" id="how-it-works"><p className="eyebrow">A LEGIBLE PATH</p><h2>From intent to an accountable mission.</h2><div className="workflow-grid"><article><b>01</b><h3>Describe or scan</h3><p>Start with an idea or a read-only reality report for an existing codebase.</p></article><article><b>02</b><h3>Review the blueprint</h3><p>See assumptions, risks, conflicts, requirements, and recommended defaults.</p></article><article><b>03</b><h3>Seal the boundary</h3><p>Rust authority locks scope and task order. The interface cannot invent approval.</p></article><article><b>04</b><h3>Watch and verify</h3><p>Observe actual execution, safe recovery, blockers, and evidence-backed completion.</p></article></div></section>
    <section className="audience-grid"><div id="new-project"><p className="eyebrow">NEW PROJECT</p><h2>Make the idea legible.</h2><p>Not sure is a valid answer. Relintor explains why a decision matters and keeps the unresolved boundary visible.</p><a className="text-link" href="#top">Start from an idea →</a></div><div id="takeover"><p className="eyebrow">EXISTING PROJECT</p><h2>Take over with evidence.</h2><p>The initial scan is read-only. Keep, repair, remove, or rebuild only after the reality report and blueprint are understood.</p><a className="text-link" href="#top">Inspect a codebase →</a></div></section>
    <footer><img className="footer-brand-logo" src="/relintor-logo.png" alt="Relintor" /><span>Don’t trust done. Prove it.</span><span>© 2026</span></footer>
  </main>;
}
